"""
load_data.py
------------
Loads all 100 transcript folders into a single clean pandas DataFrame.

Each transcript folder contains:
  - meeting-info.json   -> title, host, emails, start/end time, duration
  - summary.json        -> pre-existing LLM-generated summary, topics,
                            overallSentiment, sentimentScore, actionItems,
                            keyMoments (this is "baseline" data shipped
                            with the dataset, NOT something we generated)
  - transcript.json      -> sentence-level transcript with per-sentence
                            sentimentType (also baseline/pre-existing)
  - speakers.json / speaker-meta.json / events.json -> speaker timing,
                            join/leave events (not used in v1 of this
                            pipeline, but loaded for completeness /
                            possible future use, e.g. talk-time-share
                            insight)

Design decision: call_type (support / external / internal) is NOT present
in the raw data. We derive it from a simple, transparent heuristic:
  - title contains "Support Case" -> support
  - all participant emails share the @aegiscloud.com domain -> internal
  - otherwise (aegiscloud.com + at least one external domain) -> external

This heuristic was validated by eyeballing all 100 titles -- it cleanly
separates the data into 43 external / 30 internal / 27 support calls,
which matches the assignment's three call types without needing any
relabeling or synthetic data.
"""

import json
import os
import re
import pandas as pd

RAW_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "raw_transcripts")


def classify_call_type(title: str, emails: list[str]) -> str:
    external_domains = {e.split("@")[-1] for e in emails} - {"aegiscloud.com"}
    if re.search(r"support case", title, re.IGNORECASE):
        return "support"
    if len(external_domains) == 0:
        return "internal"
    return "external"


def get_customer_company(call_type: str, emails: list[str]) -> str | None:
    """Best-effort customer company name derived from the non-aegiscloud
    email domain, for external/support calls. Internal calls return None."""
    if call_type == "internal":
        return None
    ext_domains = sorted({e.split("@")[-1] for e in emails} - {"aegiscloud.com"})
    if not ext_domains:
        return None
    domain = ext_domains[0]
    # turn "summittrust.com" into "Summittrust" as a rough display name;
    # the meeting title usually has a nicer human name (e.g. "Summit Trust")
    return domain.split(".")[0]


def load_transcript_text(folder: str) -> str:
    """Concatenate sentence-level transcript into a single text blob,
    formatted as 'Speaker: sentence' per line, for LLM prompting."""
    path = os.path.join(folder, "transcript.json")
    with open(path) as f:
        data = json.load(f)["data"]
    lines = [f"{turn['speaker_name']}: {turn['sentence']}" for turn in data]
    return "\n".join(lines)


def load_all_transcripts() -> pd.DataFrame:
    rows = []
    folder_ids = sorted(
        f for f in os.listdir(RAW_DIR) if os.path.isdir(os.path.join(RAW_DIR, f))
    )

    for fid in folder_ids:
        folder = os.path.join(RAW_DIR, fid)
        with open(os.path.join(folder, "meeting-info.json")) as f:
            mi = json.load(f)
        with open(os.path.join(folder, "summary.json")) as f:
            sm = json.load(f)

        call_type = classify_call_type(mi["title"], mi["allEmails"])
        company = get_customer_company(call_type, mi["allEmails"])
        full_text = load_transcript_text(folder)

        rows.append(
            {
                "call_id": fid,
                "title": mi["title"],
                "call_type": call_type,
                "company": company,
                "host": mi.get("host"),
                "all_emails": mi.get("allEmails", []),
                "num_participants": len(mi.get("allEmails", [])),
                "start_time": mi.get("startTime"),
                "duration_min": mi.get("duration"),
                "transcript_text": full_text,
                # --- baseline fields shipped with the dataset (pre-existing,
                # NOT generated by our pipeline) -- used later to validate
                # our own categorization/sentiment output against ---
                "baseline_summary": sm.get("summary"),
                "baseline_topics": sm.get("topics", []),
                "baseline_sentiment_label": sm.get("overallSentiment"),
                "baseline_sentiment_score": sm.get("sentimentScore"),
                "baseline_action_items": sm.get("actionItems", []),
                "baseline_key_moments": sm.get("keyMoments", []),
            }
        )

    df = pd.DataFrame(rows)
    df["start_time"] = pd.to_datetime(df["start_time"])
    return df


if __name__ == "__main__":
    df = load_all_transcripts()
    print(df.shape)
    print(df["call_type"].value_counts())
    print(df[["call_id", "title", "call_type", "company", "duration_min"]].head(10))
